# 第二章 Go的内部机制

All the Go features that you learned in the previous chapter are extremely handy and you will be using them all the time. However, there is nothing as rewarding as being able to see and understand what is going on in the background and how Go operates behind the scenes.

In this chapter, you are going to learn about the Go garbage collector and the way it works. Additionally, you will find out how to call C code from your Go programs, which you might find indispensable in some situations. However, you will not need to use this capability too often because Go is a very capable programming language.

Furthermore, you will learn how to call Go code from your C programs, along with how to use the panic() and recover() functions and the defer keyword.

This chapter covers:

The Go compiler
How garbage collection works in Go
How to check the operation of the garbage collector
Calling C code from your Go code
Calling Go code from a C program
The panic() and recover() functions
The unsafe package
The handy, yet tricky, defer keyword
The strace(1) Linux utility
The dtrace(1) utility, which can be found in FreeBSD systems, including macOS Mojave
Finding out information about your Go environment
The node trees created by Go
Creating WebAssembly code from Go
The Go assembler

本章学习以下内容：

- Go编译器
- Go的垃圾回收是如何工作的
- 如何检查垃圾回收器的操作
- 在Go代码中调用C代码
- 在C程序中调用Go代码
- 函数`panic()`和`recover()`
- `unsafe`包
- 方便且具有技巧性的`defer`关键字
- Linux工具`strace(1)`
- FreeBSD和MacOS中的工具`dstrace(1)`
- Go环境变量的更多内容
- Go所创建的node tree
- 用Go创建WebAssembly代码
- Go的汇编器

## Go编译器

The Go compiler is executed with the help of the go tool, which does many more things
than just generating executable files.

## 垃圾回收

## 在Go中调用C代码

## 在C代码中调用Go函数

## 关键字defer

The defer keyword postpones the execution of a function until the surrounding function
returns, which is widely used in file input and output operations because it saves you from
having to remember when to close an opened file. The defer keyword allows you to put
the function call that closes an opened file near to the function call that opened it. As you
will learn about the use of defer in file-related operations in Chapter 8 , Telling a UNIX
System What to Do, this section will present two different usages of defer . You will also see
defer in action in the section that talks about the panic() and recover() built-in Go
functions, as well as in the section that is related to logging.

关键字defer延缓了被包裹函数的执行，直到有结果返回，它被广泛用于文件输入和输出的操作上，因为它免去了你必须记住对已打开文件进行关闭的麻烦。关键字`defer`允许你调用

It is very important to remember that deferred functions are executed in last in, first out
(LIFO) order after the return of the surrounding function. Putting it simply, this means that
if you defer function f1() first, function f2() second, and function f3() third in the
same surrounding function, when the surrounding function is about to return, function
f3() will be executed first, function f2() will be executed second, and function f1() will
be the last one to get executed.

非常重要的一点是你要记住使用了defer的函数在包裹的函数返回之后按照后进先出的顺序来执行。简单来说，就是如果你在同一个包裹函数中分别按照顺序对f1()，f2()，f3()使用defer，那么在包裹函数执行返回时，那么函数f3()将被第一个执行，

As this definition of defer is a little unclear, I think that you will understand the use of
defer a little better by looking at the Go code and the output of the defer.go program,
which will be presented in three parts.

而defer这种定义不是那么清晰，我认为你想要多理解defer的使用，最好看看Go的代码和程序defer.go的输出，该程序由三个部分组成。

Apart from the import block, the preceding Go code implements a function named d1()
with a for loop and a defer statement that will be executed three times.

第一部分为导入，和函数d1()的实现

In this part of the code, you can see the implementation of another function, which is
named d2() . The d2() function also contains a for loop and a defer statement, which
will also be executed three times. However, this time, the defer keyword is applied to an
anonymous function instead of a single fmt.Print() statement. Additionally, the
anonymous function takes no parameters.

第二部分的代码，你可以看到另外一个函数的实现，即d2()。函数d2()包含了一个for循环和一个defer语句，而这个defer语句将被执行三次。不过，这次关键字defer用在了匿名函数身上，而不是单独的fmt.Print()语句。此外，这个匿名函数不接受参数。

```go
package main

import (
    "fmt"
)

func d1() {
    for i := 3; i > 0; i-- {
        defer fmt.Print(i, " ")
    }
}

func d2() {
    for i := 3; i > 0; i-- {
        defer func() {
            fmt.Print(i, " ")
        }()
    }
    fmt.Println()
}

func d3() {
    for i := 3; i > 0; i-- {
        defer func(n int) {
            fmt.Print(n, " ")
        }(i)
    }
}

func main() {
    d1()
    d2()
    fmt.Println()
    d3()
    fmt.Println()
}
```

输出结果：

```bash
➜  go run defer.go
1 2 3
0 0 0
1 2 3
```

You will most likely find the generated output complicated and challenging to understand.
This underscores the fact that the operation and the results of the use of defer can be tricky
if your code is not clear and unambiguous.

你最终会发现生成输出的复杂，以及理解上的挑战。

Let's examine the results in order to get a better idea of how tricky defer can be if you do
not pay close attention to your code. We will start with the first line of the output ( 1 2 3 ),
which is generated by the d1() function. The values of i in d1() are 3 , 2 , and 1 in that
order. The function that is deferred in d1() is the fmt.Print() statement. As a result,
when the d1() function is about to return, you get the three values of the i variable of the
for loop in reverse order because deferred functions are executed in LIFO order.

我们来按顺序验证以下结果，以便更好地理解当你你不想过多关心代码的关闭时的defer的巧妙运用。我们从第一行的输出结果开始，它由函数d1()生成。d1()中i的值，按照3、2、1的顺序。该函数在d1()中所`defer`的是`fmt.Print()`语句。

Now, let's inspect the second line of the output that is produced by the d2() function. It is
really strange that we got three zeros instead of 1 2 3 in the output. The reason for this,
however, is relatively simple. After the for loop has ended, the value of i is 0 , because it is
that value of i that made the for loop terminate. However, the tricky part here is that the
deferred anonymous function is evaluated after the for loop ends, because it has no
parameters. This means that is evaluated three times for an i value of 0 , hence the
generated output! This kind of confusing code is what might lead to the creation of nasty
bugs in your projects, so try to avoid it!

现在，我们检查函数`d2()`所产生的第二行输出。很奇怪，输出中我们得到是三个0，而不是1、2、3。不过，发生这种情况的原因是相当简单。在for循环结束之后，i的值是0，因为就是这个i的值使循环终止。然而，这里要小心是，被`defer`的匿名函数在循环结束后才进行求职，因为这个匿名函数没有参数。这就意味着将i的值0进行了三次计算，由此输出随之产生！这种迷惑人的代码会导致你在项目中出现恼人的bug，所以试着避免这样做。

Also, we will talk about the third line of the output, which is generated by the d3()
function. Due to the parameter of the anonymous function, each time the anonymous
function is deferred, it gets and uses the current value of i . As a result, each execution of the
anonymous function has a different value to process, thus the generated output.

接着，我们来说下第三行的输出，它由函数d3()生成。为了处理匿名函数参数，每次匿名函数都用上了defer，

After this, it should be clear that the best approach to the use of defer is the third one,
which is exhibited in the d3() function. This is so because you intentionally pass the
desired variable in the anonymous function in an easy to understand way.

打这以后，你应该能够清楚的明白使用defer的最佳方式就是第三个，即，函数d()中的用法。就这么简单，以易于理解的方式就是你把刻意地把希望使用的变量传递到匿名函数。

### 使用defer做日志记录

This section will present an application of defer related to logging. The purpose of this
technique is to help you organize the logging information of a function in a better way and
make it more visible. The name of the Go program that will illustrate the use of the defer
keyword in logging is logDefer.go and it will be presented in three parts.

这一小节会有一个与defer有关的日志程序。

The function named one() is using defer to make sure that the second aLog.Println()
call is going to be executed just before the function is about to return. Therefore, all log
messages from the function are going to be embedded between the opening
aLog.Println() and the closing aLog.Println() calls. As a result, it will be much easier
to discover the log messages of that function in your log files.

函数one()使用defer是为了保证第二个`aLog.Println()`的调用能够在函数返回之前被执行。因此，所有的日志消息

The function named two() also uses defer to easily group its log messages. However, this
time two() uses slightly different messages than function one() . It is up to you to choose
the format of the logging messages.

函数`two()`也使用defer很容易地组织起自己的日志消息。不过，这次`two()`的使用的与`one()`略有不同的消息。选择何种日志消息格式化你自己决定。

```go
/*
logDefer.go
*/
package main

import (
    "fmt"
    "log"
    "os"
)

var LOGFILE = "/tmp/mGo.log"

func one(aLog *log.Logger) {
    aLog.Println("-- FUNCTION one ------")
    defer aLog.Println("-- FUNCTION one ------")

    for i := 0; i < 10; i++ {
        aLog.Println(i)
    }
}

func two(aLog *log.Logger) {
    aLog.Println("---- FUNCTION two")
    defer aLog.Println("FUNCTION two ------")

    for i := 10; i > 0; i-- {
        aLog.Println(i)
    }
}

func main() {
    f, err := os.OpenFile(LOGFILE, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
    if err != nil {
        fmt.Println(err)
        return
    }
    defer f.Close()

    iLog := log.New(f, "logDefer ", log.LstdFlags)
    iLog.Println("Hello there!")
    iLog.Println("Another log entry!")

    one(iLog)
    two(iLog)
}
```

Executing logDefer.go will generate no visible output. However, looking at the contents
of /tmp/mGo.log , which is the log file that is being used by the program, will make it
pretty clear how handy the use of defer is in this case:

执行`logDefer.go`不会生成可见输出。不过，你看下/tmp/mGo.log的内容

```shell
$ go run panicRecover.go
Inside a()
About to call b()
Inside b()
Recover inside a()!
main() ended!
```

What just happened here is really impressive! However, as you can see from the output, the
a() function did not end normally, because its last two statements did not get executed:

```go
fmt.Println("b() exited!")
fmt.Println("Exiting a()")
```

Nevertheless, the good thing is that panicRecover.go ended according to our will
without panicking because the anonymous function used in defer took control of the
situation! Also note that function b() knows nothing about function a() . However,
function a() contains Go code that handles the panic condition of the b() function!

### Using the panic function on its own

You can also use the panic() function on its own without any attempt to recover, and this
subsection will show you its results using the Go code of justPanic.go , which will be
presented in two parts.

The first part of justPanic.go follows next:
